---
- name: "Ensure logrotate is configured"
  template:
    src: logrotate.d/docker-typo3.j2
    dest: /etc/logrotate.d/docker-typo3-{{ instance }}
- name: "Create Logrotate File for NGINX"
  template:
    src: logrotate.d/docker_nginx_reverse_proxy
    dest: /etc/logrotate.d/
