---
#
# Ensure all docker containers are started
#

- include: docker_containers/db.yml state=started
- include: docker_containers/elasticsearch.yml state=started
- include: docker_containers/solr.yml state=started
- include: docker_containers/phpfpm.yml state=started
- include: docker_containers/phpfpm-ext-db.yml state=started
- include: docker_containers/web.yml state=started
