---

- set_fact:
    links: []

- name: link db container
  set_fact:
    links: "{{links}} + [ instance + '-db:db' ]"
  when: docker_containers.db is defined

- name: link solr container
  set_fact:
    links: "{{links}} + [ instance + '-solr:solr' ]"
  when: docker_containers.solr is defined

- name: link elasticsearch container
  set_fact:
    links: "{{links}} + [ instance + '-elasticsearch:elasticsearch' ]"
  when: docker_containers.elasticsearch is defined

- name: set default volumes
  set_fact:
    volumes:
      - "{{ instance_data_root_folder }}web:/data/web"
      - "{{ instance_data_root_folder }}log:/data/log"
      - "{{ instance_data_root_folder }}cron.d:/etc/cron.d"
      - "{{ instance_ca_certificates_folder }}:/usr/local/share/ca-certificates"

- name: add transfer_folders to volumes
  set_fact:
    volumes: "{{ volumes }} + {{ transfer_folders }}"
  when: transfer_folders

- name: "{{ instance }}: ensure phpfpm container is {{ state }}"
  docker:
    name: "{{ instance }}-phpfpm"
    image: "{{ docker_images.phpfpm }}:{{ docker_containers.phpfpm.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
    env:
      APPLICATION_TYPE: "{{ application_type | upper() }}"
      TYPO3_CONTEXT: "{{ typo3_context }}"
      FLOW_CONTEXT: "{{ flow_context }}"
      DOMAINS: "{{ domain_list }}"
      DOMAIN_LIST: "{{ domain_list }}"
      PRIMARY_DOMAIN: "{{ primary_domain }}"
      PRIMARY_SCHEMA: "{{ primary_schema }}"
      SSMTP_ROOT: "{{ ssmtp_root }}"
      SSMTP_MAILHUB: "{{ ssmtp_mailhub }}"
      SSMTP_HOSTNAME: "{{ ssmtp_hostname }}"
      ENCRYPTION_KEY: "{{ encryption_key }}"
      PIWIK_URL: "{{ piwik_url }}"
      PIWIK_TOKEN: "{{ piwik_token }}"
      PHP_SESSION_INI_DIR: "{{ php_session_ini_dir }}"
      PHP_SESSION_SAVE_HANDLER: "{{ php_session_save_handler }}"
      PHP_SESSION_SAVE_PATH: "{{ php_session_save_path }}"
      PROXYPASS_URL: "{{ proxypass_url }}"
      PROXYPASS_TSCONST_PIDMONEYCOMPUTER: "{{ proxypass_tsconst_pidmoneycomputer }}"
      THOMSONREUTERSQUOTESADAPTER_CREDENTIALS_APPID: "{{ thomsonreutersquotesadapter_credentials_appid }}"
      THOMSONREUTERSQUOTESADAPTER_CREDENTIALS_SERVICEUSERNAME: "{{ thomsonreutersquotesadapter_credentials_serviceusername }}"
      THOMSONREUTERSQUOTESADAPTER_CREDENTIALS_PASSWORD: "{{ thomsonreutersquotesadapter_credentials_password }}"
      MADPORT_MAIL_FROMADDRESS: "{{ madport_mail_fromaddress }}"
      MADPORT_MAIL_FROMNAME: "{{ madport_mail_fromname }}"
      MADPORT_CONTEXT: "{{ madport_context }}"
      MADPORT_MAIL_ENABLED: "{{ madport_mail_enabled }}"
      MADPORT_MAIL_RECEIVER: "{{ madport_mail_receiver }}"
      MADPORT_SMS_ENABLED: "{{ madport_sms_enabled }}"
      MADPORT_SMS_RECEIVER: "{{ madport_sms_receiver }}"
      MADPORT_API_LOGIN_URL: "{{ madport_api_login_url }}"
      MADPORT_API_PARENTORGID: "{{ madport_api_parentorgid }}"
      MADPORT_API_LOGINNAME: "{{ madport_api_loginname }}"
      MADPORT_API_PASSWORD: "{{ madport_api_password }}"
      MADPORT_API_FETCHALERTS_URL: "{{ madport_api_fetchalerts_url }}"
      MADPORT_API_COMMITALERTS_URL: "{{ madport_api_commitalerts_url }}"
    links: "{{ links }}"
    volumes: "{{ volumes }}"
    extra_hosts; "{{ extra_hosts }}"
  when: docker_containers.phpfpm is defined
