---

- set_fact:
    links: []

- name: link db container
  set_fact: 
    links: "{{links}} + [ instance + '-db:db' ]"
  when: docker_containers.db is defined

- name: link solr container
  set_fact:
    links: "{{links}} + [ instance + '-solr:solr' ]"
  when: docker_containers.solr is defined


- name: set default volumes
  set_fact:
    volumes:
      - "{{ instance_data_root_folder }}web:/data/web"
      - "{{ instance_data_root_folder }}log:/data/log"
      - "{{ instance_data_root_folder }}cron.d:/etc/cron.d"
      - "{{ instance_ca_certificates_folder }}:/usr/local/share/ca-certificates"

- name: add transfer_folders to volumes
  set_fact:
    volumes: "{{ volumes }} + {{ transfer_folders }}"
  when: transfer_folders

- name: "{{ instance }}: ensure phpfpm container is {{ state }}"
  docker:
    name: "{{ instance }}-phpfpm"
    image: "{{ docker_images.phpfpm }}:{{ docker_containers.phpfpm.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
    env:
      APPLICATION_TYPE: "{{ application_type | upper() }}"
      TYPO3_CONTEXT: 'Production'
      FLOW_CONTEXT: 'Production'
      DOMAINS: "{{ domain_list }}"
      DOMAIN_LIST: "{{ domain_list }}"
      PRIMARY_DOMAIN: "{{ primary_domain }}"
      PRIMARY_SCHEMA: "{{ primary_schema }}"
      SSMTP_ROOT: "{{ ssmtp_root }}"
      SSMTP_MAILHUB: "{{ ssmtp_mailhub }}"
      SSMTP_HOSTNAME: "{{ ssmtp_hostname }}"
    links: "{{ links }}"
    volumes: "{{ volumes }}"
  when: docker_containers.phpfpm is defined
