---
- name: "{{ instance }}: ensure phpfpm container is {{ state }}"
  docker:
    name: "{{ instance }}-phpfpm"
    image: "{{ docker_images.phpfpm }}:{{ docker_containers.phpfpm.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
    env:
      APPLICATION_TYPE: "{{ application_type | upper() }}"
    links:
      - "{{ instance }}-db:db"
    volumes:
      - "{{ instance_data_root_folder }}web:/data/web"
  when: docker_containers.phpfpm is defined