---

- set_fact:
    links: []

- name: link db container
  set_fact: 
    links: "{{links}} + [ instance + '-db:db' ]"
  when: docker_containers.db is defined

- name: "{{ instance }}: ensure phpfpm container is {{ state }}"
  docker:
    name: "{{ instance }}-phpfpm"
    image: "{{ docker_images.phpfpm }}:{{ docker_containers.phpfpm.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
    env:
      APPLICATION_TYPE: "{{ application_type | upper() }}"
    links: "{{ links }}"
    volumes:
      - "{{ instance_data_root_folder }}web:/data/web"
  when: docker_containers.phpfpm is defined