---
- name: "{{ instance }} create solr log folder and ensure access rights"
  file:
    path: "{{ instance_data_root_folder }}/log/solr"
    owner: 8983
    group: 8983
    state: directory
  register: solr_log_folder

- name: "{{ instance }}: ensure solr container is {{ state }}"
  docker:
    name: "{{ instance }}-solr"
    image: "{{ docker_images.solr }}:{{ docker_containers.solr.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
#    pull: "{%if pull_docker_images == 'yes'%}always{% else %}missing{% endif %}"
    env:
      SOLR_ENABLE_MASTER: "{{ solr_enable_master }}"
      SOLR_ENABLE_SLAVE: "{{ solr_enable_slave }}"
      SOLR_MASTER_HOST: "{{ solr_master_host }}"
      SOLR_MASTER_PORT: "{{ solr_master_port }}"
    volumes:
      - "{{ instance_data_root_folder }}solr:/opt/solr-tomcat/solr/typo3cores/data"
      - "{{ instance_data_root_folder }}solr:/opt/solr/server/solr/data"
      - "{{ solr_log_folder.path }}:/opt/solr/server/logs"
    expose:
      - 8983
    ports:
      - "{{ solr_port }}:8983"
  when: docker_containers.solr is defined
