---
- name: "{{ instance }}: ensure web container is {{ state }}"
  docker:
    name: "{{ instance }}-web"
    image: "{{ docker_images.web }}:{{ docker_containers.web.image_tag }}"
    state: "{{ state }}"
    restart_policy: always
    env:
      VIRTUAL_HOST: "{{ instance }}.{{ global_base_domain }}{% if domains|length %},{% endif %}{{ domains|join(',') }}"
    links:
      - "{{ instance }}-phpfpm:phpfpm"
    volumes:
      - "{{ instance_data_root_folder }}web:/data/web"
      - "{{ instance_data_root_folder }}nginx/custom:/etc/nginx/conf.d/custom"
  when: docker_containers.web is defined
